# Generated by Django 4.2.16 on 2026-06-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanelAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_sudo', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('total_user_limit', models.BigIntegerField(default=0, help_text='Sum of all user data limits (bytes)')),
                ('total_user_used', models.BigIntegerField(default=0, help_text='Sum of all traffic used by users (bytes)')),
                ('admin_remaining', models.BigIntegerField(default=0, help_text="Admin's own remaining quota from panel (bytes)")),
                ('user_count', models.IntegerField(default=0)),
                ('active_user_count', models.IntegerField(default=0)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Panel Admin',
                'verbose_name_plural': 'Panel Admins',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], max_length=20)),
                ('admins_synced', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('duration_seconds', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
