# Generated by Django 4.2.16 on 2026-06-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paneladmin',
            name='admin_limit_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paneladmin',
            name='disabled_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paneladmin',
            name='expired_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paneladmin',
            name='limited_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paneladmin',
            name='on_hold_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paneladmin',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='paneladmin',
            name='admin_remaining',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paneladmin',
            name='total_user_limit',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paneladmin',
            name='total_user_used',
            field=models.BigIntegerField(default=0),
        ),
    ]
