# Generated by Django 4.2.16 on 2026-06-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_paneladmin_admin_limit_bytes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_minutes', models.IntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sync Settings',
            },
        ),
        migrations.AddField(
            model_name='paneladmin',
            name='has_data_limit',
            field=models.BooleanField(default=False, help_text='False = unlimited admin'),
        ),
    ]
