# Generated by Django 4.2.16 on 2026-06-19 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_syncsettings_paneladmin_has_data_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='paneladmin',
            name='pamp_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paneladmin',
            name='pamp_blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paneladmin',
            name='has_data_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AdminLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_bytes', models.BigIntegerField(default=0)),
                ('warning_sent_80', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('support_telegram', models.CharField(blank=True, default='@support', max_length=100)),
                ('panel_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limit_config', to='admins.paneladmin')),
            ],
            options={
                'verbose_name': 'Admin Limit Config',
                'verbose_name_plural': 'Admin Limit Configs',
            },
        ),
    ]
