# Generated by Django 4.2.16 on 2026-06-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_paneladmin_pamp_blocked_paneladmin_pamp_blocked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Panel Configuration',
            },
        ),
    ]
