# Generated by Django 4.2.16 on 2026-07-16 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_panelconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='paneladmin',
            name='deleted_traffic_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paneladmin',
            name='deleted_users_used_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserTrafficSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(max_length=255)),
                ('used_traffic_bytes', models.BigIntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('panel_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_snapshots', to='admins.paneladmin')),
            ],
            options={
                'indexes': [models.Index(fields=['panel_admin', 'user_username'], name='admins_user_panel_a_7ad2b2_idx')],
                'unique_together': {('panel_admin', 'user_username')},
            },
        ),
    ]
