# Generated by Django 4.2.16 on 2026-08-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_paneladmin_deleted_traffic_reset_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('v1', 'Classic'), ('v2', 'Modern')], default='v2', max_length=10)),
            ],
            options={
                'verbose_name': 'UI Settings',
            },
        ),
    ]
