# Generated by Django 4.2.16 on 2026-08-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_uisettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, max_length=255)),
                ('chat_id', models.CharField(blank=True, max_length=100)),
                ('backup_interval_hours', models.PositiveIntegerField(default=24)),
                ('is_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Config',
            },
        ),
    ]
