# Generated by Django 4.2.16 on 2026-08-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_telegram_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_username', models.CharField(help_text='The admin username who logs in and sees all member accounts', max_length=150, unique=True)),
                ('member_usernames', models.TextField(blank=True, help_text='Comma-separated list of admin usernames in this group')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Account Group',
            },
        ),
    ]
